services:
  dns-proxy:
    image: vimagick/tinyproxy
    ports:
      - "8888:8888"
    dns:
      # 403
      - 10.202.10.202
      - 10.202.10.102

      # Begzar
      #- 185.55.226.26
      #- 185.55.225.25

      # Shecan
      #- 178.22.122.100
      #- 185.51.200.2

      # Electro
      #- 78.157.42.101
      #- 78.157.42.100

    restart: unless-stopped

